#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Jagadeesh Chandra Muddana <mjchandra@gmail.com>
#
# Assembles the published ABI artifact: one tar carrying everything needed to
# target this system without holding this tree.
#
# **What goes in, and why each of it.** The schemas, because they are the
# definition. The compiled IR beside them, because that is what the digests in
# `surface.lock` are over, so a consumer can verify the artifact with
# `sha256sum` and nothing from here. The reference pages, because a definition
# nobody can read is not published. The generated bindings *and a BUILD file
# declaring them*, because "builds against the artifact" is the only test of a
# published ABI that cannot be satisfied by intending to. The wire runtime and
# `uabi`, because bindings that call a runtime the consumer does not have are
# not an artifact, they are a bill of materials.
#
# **Deterministic.** `tar` is given a fixed mtime, owner, group and sort order:
# an artifact whose digest changes because it was built on a Tuesday cannot be
# the thing a version refers to.
#
# Usage: mkabi.sh <out.tar> <surface.lock> <README.md> <islc>
#          --schemas <file>... --bindings <file>... --tree <prefix> <file>...
# `--tree` takes a source prefix to strip, so a whole package lands under its
# own path in the artifact and this script never guesses a layout.
# Normative: docs/api/03-interface-schema-language.md ("Generated Artifacts"),
# docs/roadmap/03-composition-and-self-hosting.md ("Phase 4")
set -euo pipefail

out="${1:?usage: mkabi.sh <out.tar> <surface.lock> <README.md> <islc> ...}"
lock="${2:?missing surface.lock}"
readme="${3:?missing README.md}"
islc="${4:?missing islc}"
shift 4

version="$(sed -n 's/^abi-version *= *//p' "$lock" | head -1)"
[ -n "$version" ] || { echo "mkabi: no abi-version in $lock" >&2; exit 1; }
root="tessera-abi-$version"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
stage="$work/$root"
mkdir -p "$stage/schemas" "$stage/ir" "$stage/reference" \
    "$stage/api/isl" "$stage/api/isl-runtime" "$stage/userspace/uabi"

cp "$lock" "$stage/surface.lock"
cp "$readme" "$stage/README.md"
echo "$version" >"$stage/VERSION"

# Everything the caller staged. `--schemas` and `--bindings` are flat sets
# whose file names are their identity; `--tree <prefix>` is a whole package,
# reproduced under its own path so the BUILD file beside it still resolves.
mode=""
prefix=""
for arg in "$@"; do
    case "$arg" in
        --schemas | --bindings)
            mode="$arg"
            continue
            ;;
        --tree)
            mode="$arg"
            prefix=""
            continue
            ;;
    esac
    case "$mode" in
        --schemas) cp "$arg" "$stage/schemas/$(basename "$arg")" ;;
        --bindings) cp "$arg" "$stage/api/isl/$(basename "$arg")" ;;
        --tree)
            if [ -z "$prefix" ]; then
                prefix="$arg"
                continue
            fi
            rel="${arg#"$prefix"}"
            rel="${rel#/}"
            mkdir -p "$stage/$prefix/$(dirname "$rel")"
            cp "$arg" "$stage/$prefix/$rel"
            ;;
        *)
            echo "mkabi: '$arg' before any of --schemas/--bindings/--tree" >&2
            exit 2
            ;;
    esac
done

# The schemas are the definition; the IR is what the lock's digests are over,
# and the reference is the readable form. All three from the one compiler, so
# they cannot describe different surfaces.
schemas=0
for schema in "$stage"/schemas/*.isl; do
    name="$(basename "$schema" .isl)"
    "$islc" emit-ir "$schema" >"$stage/ir/$name.ir"
    "$islc" emit-docs "$schema" >"$stage/reference/$name.md"
    schemas=$((schemas + 1))
done
# A loop over an empty directory leaves a clean exit and an empty artifact,
# which reads as a published ABI for ever.
[ "$schemas" -gt 0 ] || { echo "mkabi: no schemas staged" >&2; exit 1; }

# The BUILD file that makes this an artifact a tree can compile against rather
# than a directory it can read. Each staged file is named `<label>.<crate>.rs`
# by `//build/rules:isl.bzl`, because for two schemas the label, the crate and
# the schema name are three different words — `firmware.isl` is crate
# `firmware_abi` behind `:firmware_bindings` — and a convention with exceptions
# is not something to re-derive here. Everything is public: a published
# interface has no internal visibility policy, which is what publishing means.
crates=0
{
    echo "# @generated by api/abi/mkabi.sh — the published ABI's own build file."
    echo '# SPDX-License-Identifier: Apache-2.0'
    echo
    echo 'load("@rules_rust//rust:defs.bzl", "rust_library")'
    echo
    for staged in "$stage"/api/isl/*.rs; do
        base="$(basename "$staged" .rs)"
        label="${base%%.*}"
        crate="${base#*.}"
        if [ "$label" = "$crate" ] || [ -z "$crate" ]; then
            echo "mkabi: '$base' is not <label>.<crate>.rs" >&2
            exit 1
        fi
        crates=$((crates + 1))
        cat <<RULE

rust_library(
    name = "${label}",
    srcs = ["${base}.rs"],
    crate_name = "${crate}",
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = ["//api/isl-runtime:isl_runtime"],
)
RULE
    done
} >"$stage/api/isl/BUILD.bazel"
[ "$crates" -gt 0 ] || { echo "mkabi: no bindings staged" >&2; exit 1; }

# What is in the artifact, measured. `surface.lock` says what the *interface*
# is; this says what the *file set* is, which is the other half of being able
# to check that what arrived is what was published.
(
    cd "$stage"
    find . -type f ! -name MANIFEST -print0 |
        LC_ALL=C sort -z |
        xargs -0 sha256sum |
        sed 's|\./||'
) >"$stage/MANIFEST"

tar --create --file "$out" \
    --directory "$work" \
    --sort=name --mtime='UTC 2026-01-01' \
    --owner=0 --group=0 --numeric-owner \
    --format=ustar \
    "$root"

printf 'abi: %s — %d schema(s), %d bindings crate(s)\n' "$root" "$schemas" "$crates" >&2
