#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Jagadeesh Chandra Muddana <mjchandra@gmail.com>
#
# Builds the tree's documentation: the generated interface reference, one page
# per ISL schema, and the API documentation for every host-buildable crate.
#
# **Why this exists.** `docs/api/03` has listed reference documentation among
# the artifacts generated from one schema since it was written, and nothing
# generated it; `cargo doc` appeared in no script here, so the `karch` traits
# and the `kcore` modules — documented to a standard most kernels never reach —
# were readable only by opening the tree. Both are now produced by one command,
# which is also what makes them checkable: a page that nothing builds is a page
# nothing notices has stopped building.
#
# Output goes under `build-out/docs/` and is never committed
# (docs/lifecycle/04-coding-guidelines.md, "Never edit or check in generated
# code"). Run with `--check` to build without keeping the output, which is what
# CI wants: the artifact is the proof that it builds, not something to publish
# from here.
#
# Requires: bazelisk (for islc) and cargo.
# Normative: docs/api/03-interface-schema-language.md ("Generated Artifacts"),
# docs/lifecycle/02-build-and-test-infrastructure.md ("CI Topology")
set -euo pipefail

cd "$(dirname "$0")/../.."
out="build-out/docs"
check_only=0
[ "${1:-}" = "--check" ] && check_only=1

printf '\n=== the interface reference (one page per schema)\n'
bazel build //api/isl:islc --config=ci >/dev/null
islc="$(bazel cquery //api/isl:islc --config=ci --output=files 2>/dev/null | tail -1)"
if [ ! -x "$islc" ]; then
    echo "docs: cannot find islc at '$islc'" >&2
    exit 1
fi

mkdir -p "$out/interfaces"
index="$out/interfaces/README.md"
{
    echo "<!-- @generated by tools/ci/docs.sh — do not edit. -->"
    echo "# Interface Reference"
    echo
    echo "Generated from the schemas in \`api/isl/examples\`. Every page"
    echo "describes what exists; the design documents in \`docs/api\` describe"
    echo "what is intended. See \`docs/api/01-system-call-interface.md\`."
    echo
} >"$index"

count=0
for schema in api/isl/examples/*.isl; do
    name="$(basename "$schema" .isl)"
    "$islc" emit-docs "$schema" >"$out/interfaces/$name.md"
    echo "- [\`$name\`]($name.md)" >>"$index"
    count=$((count + 1))
done
# A loop that generated nothing would leave a clean exit and an empty
# directory, which reads as a passing step for ever.
if [ "$count" -eq 0 ]; then
    echo "docs: no schemas found under api/isl/examples" >&2
    exit 1
fi
printf '%d interface pages\n' "$count"

printf '\n=== rustdoc (host-buildable crates)\n'
# The workspace's `default-members`, which is exactly the host-buildable set:
# the `karch` traits, `kcore`, the ISL compiler and wire runtime, the device
# and bus libraries, and the tier-0 gates. The five architecture ports and the
# kernel binaries are excluded because they are not host-buildable at all —
# their inline assembly names registers this target does not have, so rustdoc
# fails on them exactly as `cargo build` does. Documenting those means a
# per-target invocation, which belongs beside the per-target lint pass in
# `arch-lint.sh` rather than here.
cargo doc --no-deps --document-private-items

if [ "$check_only" -eq 1 ]; then
    rm -rf "$out"
    printf '\ndocs: built and discarded (--check)\n'
else
    rm -rf "$out/rustdoc"
    cp -r target/doc "$out/rustdoc"
    printf '\ndocs: %s\n' "$out"
fi
