// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Jagadeesh Chandra Muddana <mjchandra@gmail.com>

//! Reference-documentation generation: one Markdown page per schema, emitted
//! from the same compiled IR the bindings and the fuzz targets come from.
//!
//! **Why this is a backend and not a document.** `docs/api/03` has listed
//! reference documentation among the artifacts generated from one schema since
//! it was written, and `codegen_rust.rs` and `codegen_fuzz.rs` were the only
//! two that existed. The consequence was visible rather than theoretical: the
//! real reference for the call surface was 209 lines of doc comment on
//! `kcore::syscall::SyscallNumber` — good documentation, readable only from
//! inside the kernel by somebody who already had the source — and
//! `docs/api/01` described about twenty syscall families without marking which
//! of them exist. A page written by hand beside a schema is a description of
//! the past; this one cannot disagree with the definition because it *is* the
//! definition, rendered.
//!
//! **What it says, and what it deliberately does not.** It prints what the
//! schema knows: names, numbers, layouts, rights, statuses, and the prose
//! written above each declaration. It does not print reasoning about why
//! something is deferred — that lives in the deviation ledger, which a
//! schema's own prose links to. A schema is a poor place for an argument.
//!
//! Output is byte-stable across rebuilds: declaration order is preserved and
//! nothing environment-derived is emitted. Generated documentation is a build
//! output, never committed (docs/lifecycle/04-coding-guidelines.md).
//!
//! Normative: docs/api/03-interface-schema-language.md ("Generated Artifacts"),
//! docs/api/01-system-call-interface.md
//! Budget: none (build-time tooling)

use crate::ast::{Ownership, Status};
use crate::ir::{
    Ir, IrBits, IrDecl, IrEnum, IrExtern, IrFieldType, IrMethodKind, IrOrdinalMember, IrPayload,
    IrProtocol, IrStruct, IrSyscall, IrTable, IrUnion, prim_name,
};
use std::fmt::Write as _;

/// Emits the reference page for `ir`.
pub fn emit(ir: &Ir) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "<!-- @generated by islc emit-docs — do not edit; regenerate from the schema. -->"
    );
    let _ = writeln!(out, "# `{}`\n", ir.library);
    if !ir.doc.is_empty() {
        let _ = writeln!(out, "{}\n", ir.doc);
    }

    let syscalls: Vec<&IrSyscall> = pick(ir, |d| match d {
        IrDecl::Syscall(s) => Some(s),
        _ => None,
    });
    if !syscalls.is_empty() {
        emit_syscalls(&mut out, &syscalls);
    }

    let protocols: Vec<&IrProtocol> = pick(ir, |d| match d {
        IrDecl::Protocol(p) => Some(p),
        _ => None,
    });
    for protocol in protocols {
        emit_protocol(&mut out, protocol);
    }

    let structs: Vec<&IrStruct> = pick(ir, |d| match d {
        IrDecl::Struct(s) => Some(s),
        _ => None,
    });
    if !structs.is_empty() {
        let _ = writeln!(out, "## Structures\n");
        for s in structs {
            emit_struct(&mut out, s);
        }
    }

    let tables: Vec<&IrTable> = pick(ir, |d| match d {
        IrDecl::Table(t) => Some(t),
        _ => None,
    });
    if !tables.is_empty() {
        let _ = writeln!(out, "## Tables\n");
        for t in tables {
            emit_table(&mut out, t);
        }
    }

    let unions: Vec<&IrUnion> = pick(ir, |d| match d {
        IrDecl::Union(u) => Some(u),
        _ => None,
    });
    if !unions.is_empty() {
        let _ = writeln!(out, "## Unions\n");
        for u in unions {
            emit_union(&mut out, u);
        }
    }

    let enums: Vec<&IrEnum> = pick(ir, |d| match d {
        IrDecl::Enum(e) => Some(e),
        _ => None,
    });
    if !enums.is_empty() {
        let _ = writeln!(out, "## Enumerations\n");
        for e in enums {
            emit_enum(&mut out, e);
        }
    }

    let externs: Vec<&IrExtern> = pick(ir, |d| match d {
        IrDecl::Extern(e) => Some(e),
        _ => None,
    });
    if !externs.is_empty() {
        let _ = writeln!(out, "## Types Declared Elsewhere\n");
        let _ = writeln!(
            out,
            "Named here and defined by the library that owns the subsystem \
             they describe. Their layouts are on that library's page.\n"
        );
        let _ = writeln!(out, "| Type | Library | Description |");
        let _ = writeln!(out, "|------|---------|-------------|");
        for e in externs {
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} |",
                e.name,
                e.library,
                cell(&summarize(&e.doc))
            );
        }
        let _ = writeln!(out);
    }

    let bits: Vec<&IrBits> = pick(ir, |d| match d {
        IrDecl::Bits(b) => Some(b),
        _ => None,
    });
    if !bits.is_empty() {
        let _ = writeln!(out, "## Flag Sets\n");
        for b in bits {
            emit_bits(&mut out, b);
        }
    }
    out
}

/// The declarations of one kind, in the order the schema wrote them.
fn pick<'a, T>(ir: &'a Ir, f: impl Fn(&'a IrDecl) -> Option<&'a T>) -> Vec<&'a T> {
    ir.decls.iter().filter_map(f).collect()
}

// --- system calls ---

fn emit_syscalls(out: &mut String, calls: &[&IrSyscall]) {
    let _ = writeln!(out, "## System Calls\n");
    let _ = writeln!(
        out,
        "A call takes its number in the trap's number register and up to six \
         arguments in `arg0`..`arg5`. A register whose type is written `*T` \
         holds a **user pointer** to a `T`; every other register holds the \
         value itself. Failure is one negative word for every call \
         (`docs/api/01`, \"The Result Word\"), so only the success value is \
         listed.\n"
    );
    let _ = writeln!(out, "| # | Call | Status | Since | Arguments | Returns |");
    let _ = writeln!(out, "|---|------|--------|-------|-----------|---------|");
    for call in calls {
        let args = if call.args.is_empty() {
            "—".to_owned()
        } else {
            call.args
                .iter()
                .map(|a| format!("`arg{}: {}`", a.index, a.slot.render()))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let returns = match &call.returns {
            Some(slot) => format!("`{}`", slot.render()),
            None => "`0`".to_owned(),
        };
        let _ = writeln!(
            out,
            "| {} | [`{}`](#{}) | {} | {} | {} | {} |",
            call.number,
            call.name,
            anchor(&call.name, call.number),
            call.status.as_str(),
            call.added.map_or_else(|| "—".to_owned(), |v| v.to_string()),
            cell(&args),
            cell(&returns),
        );
    }
    let _ = writeln!(out);

    for call in calls {
        let _ = writeln!(out, "### `{}` — call {}\n", call.name, call.number);
        let _ = writeln!(out, "{}\n", status_line(call.status, call.added));
        if !call.doc.is_empty() {
            let _ = writeln!(out, "{}\n", call.doc);
        }
        if !call.args.is_empty() {
            let _ = writeln!(out, "| Register | Type | Meaning |");
            let _ = writeln!(out, "|----------|------|---------|");
            for arg in &call.args {
                let _ = writeln!(
                    out,
                    "| `arg{}` | `{}` | {} |",
                    arg.index,
                    arg.slot.render(),
                    cell(&summarize(&arg.slot.doc)),
                );
            }
            let _ = writeln!(out);
        }
        match &call.returns {
            Some(slot) => {
                let _ = writeln!(
                    out,
                    "**Returns** `{}`{}\n",
                    slot.render(),
                    suffix(&summarize(&slot.doc))
                );
            }
            None => {
                let _ = writeln!(out, "**Returns** `0` on success.\n");
            }
        }
        // The rights a call needs are a property of the capability it is
        // handed, so they are read off the handle types rather than declared
        // beside the call. Collecting them here is what makes the requirement
        // visible without the reader resolving each type by hand.
        let rights = required_rights(call);
        if !rights.is_empty() {
            let _ = writeln!(out, "**Requires** {rights}\n");
        }
    }
}

/// The rights a call's register-carried handles must hold, rendered. A handle
/// arriving inside an argument struct states its own requirement in that
/// struct's field table, which is where a reader of the struct will look.
fn required_rights(call: &IrSyscall) -> String {
    let mut parts = Vec::new();
    for arg in &call.args {
        if let IrFieldType::Handle { rights_names, .. } = &arg.slot.ty
            && !rights_names.is_empty()
        {
            parts.push(format!(
                "`{{{}}}` on `arg{}`",
                rights_names.join(", "),
                arg.index
            ));
        }
    }
    parts.join(", ")
}

// --- protocols ---

fn emit_protocol(out: &mut String, p: &IrProtocol) {
    let _ = writeln!(out, "## Protocol `{}`\n", p.name);
    let _ = writeln!(out, "Interface ID `{:#018x}`.\n", p.interface_id);
    if p.status != Status::Unstated {
        let _ = writeln!(out, "{}\n", status_line(p.status, None));
    }
    if !p.doc.is_empty() {
        let _ = writeln!(out, "{}\n", p.doc);
    }
    let _ = writeln!(out, "| Ordinal | Method | Kind | Request | Response |");
    let _ = writeln!(out, "|---------|--------|------|---------|----------|");
    for m in &p.methods {
        let (kind, request, response) = match &m.kind {
            IrMethodKind::Call { request, response } => {
                ("call", payload(request), payload(response))
            }
            IrMethodKind::OneWay { request } => ("one-way", payload(request), "—".to_owned()),
            IrMethodKind::Event { payload: pl } => ("event", "—".to_owned(), payload(pl)),
            IrMethodKind::Reserved => ("reserved", "—".to_owned(), "—".to_owned()),
        };
        let name = if m.name.is_empty() {
            "—".to_owned()
        } else {
            format!("`{}`", m.name)
        };
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {} |",
            m.ordinal,
            name,
            kind,
            cell(&request),
            cell(&response)
        );
    }
    let _ = writeln!(out);
    for m in &p.methods {
        if m.doc.is_empty() && m.status == Status::Unstated {
            continue;
        }
        let _ = writeln!(out, "**`{}`** (ordinal {})\n", m.name, m.ordinal);
        if m.status != Status::Unstated {
            let _ = writeln!(out, "{}\n", status_line(m.status, None));
        }
        if !m.doc.is_empty() {
            let _ = writeln!(out, "{}\n", m.doc);
        }
    }
}

fn payload(p: &IrPayload) -> String {
    match p.type_name() {
        Some(name) => format!("`{name}`"),
        None => "—".to_owned(),
    }
}

// --- data types ---

fn emit_struct(out: &mut String, s: &IrStruct) {
    let kind = if s.abi {
        "syscall argument struct"
    } else {
        "structure"
    };
    let _ = writeln!(out, "### `{}`\n", s.name);
    let _ = writeln!(out, "{kind}, {} bytes, {}-byte aligned.\n", s.size, s.align);
    emit_status_and_doc(out, s.status, &s.doc);
    if s.fields.is_empty() {
        return;
    }
    let _ = writeln!(out, "| Offset | Size | Field | Type | Description |");
    let _ = writeln!(out, "|--------|------|-------|------|-------------|");
    for f in &s.fields {
        let _ = writeln!(
            out,
            "| {} | {} | `{}` | `{}` | {} |",
            f.offset,
            f.size,
            f.name,
            f.ty.render(),
            cell(&summarize(&f.doc))
        );
    }
    let _ = writeln!(out);
    // What each handle field demands of the capability put in it. Only the
    // fields that demand something: a `handle<Object, {}>` requires no rights,
    // and a bullet saying so would be noise in every struct that has one.
    let mut stated = false;
    for f in &s.fields {
        if let IrFieldType::Handle {
            rights_names,
            ownership,
            ..
        } = &f.ty
            && (!rights_names.is_empty() || ownership.is_some())
        {
            let mode = match ownership {
                Some(Ownership::Transfer) => ", transferred",
                Some(Ownership::Share) => ", shared",
                Some(Ownership::Snapshot) => ", snapshot",
                None => "",
            };
            let _ = writeln!(
                out,
                "- `{}` requires `{{{}}}`{mode}.",
                f.name,
                rights_names.join(", ")
            );
            stated = true;
        }
    }
    if stated {
        let _ = writeln!(out);
    }
}

fn emit_table(out: &mut String, t: &IrTable) {
    let _ = writeln!(out, "### `{}`\n", t.name);
    emit_status_and_doc(out, t.status, &t.doc);
    emit_ordinal_members(out, &t.members);
}

fn emit_union(out: &mut String, u: &IrUnion) {
    let _ = writeln!(out, "### `{}`\n", u.name);
    let _ = writeln!(
        out,
        "{} union: an unknown variant is {}.\n",
        if u.strict { "Strict" } else { "Flexible" },
        if u.strict {
            "a validation error"
        } else {
            "preserved and passed through"
        }
    );
    emit_status_and_doc(out, u.status, &u.doc);
    emit_ordinal_members(out, &u.members);
}

fn emit_ordinal_members(out: &mut String, members: &[IrOrdinalMember]) {
    if members.is_empty() {
        return;
    }
    let _ = writeln!(out, "| Ordinal | Field | Type | Description |");
    let _ = writeln!(out, "|---------|-------|------|-------------|");
    for m in members {
        let (name, ty) = match (&m.field, &m.ty) {
            (Some(name), Some(ty)) => (format!("`{name}`"), format!("`{}`", ty.render())),
            // An out-of-line member type resolves but its wire codegen is
            // deferred (D10); the page says so rather than omitting the row.
            (Some(name), None) => (format!("`{name}`"), "out-of-line (deferred)".to_owned()),
            _ => ("reserved".to_owned(), "—".to_owned()),
        };
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            m.ordinal,
            name,
            cell(&ty),
            cell(&summarize(&m.doc))
        );
    }
    let _ = writeln!(out);
}

fn emit_enum(out: &mut String, e: &IrEnum) {
    let _ = writeln!(out, "### `{}`\n", e.name);
    let _ = writeln!(
        out,
        "{} enumeration over `{}`: an unknown value is {}.\n",
        if e.strict { "Strict" } else { "Flexible" },
        prim_name(e.base),
        if e.strict {
            "a validation error"
        } else {
            "preserved and passed through"
        }
    );
    emit_status_and_doc(out, e.status, &e.doc);
    emit_values(out, "Value", &e.members, false);
}

fn emit_bits(out: &mut String, b: &IrBits) {
    let _ = writeln!(out, "### `{}`\n", b.name);
    let _ = writeln!(out, "Flag set over `{}`.\n", prim_name(b.base));
    emit_status_and_doc(out, b.status, &b.doc);
    emit_values(out, "Bit", &b.members, true);
}

fn emit_values(out: &mut String, heading: &str, members: &[crate::ir::IrValue], hex: bool) {
    if members.is_empty() {
        return;
    }
    let _ = writeln!(out, "| {heading} | Name | Description |");
    let _ = writeln!(out, "|-------|------|-------------|");
    for m in members {
        let value = if hex {
            format!("`{:#x}`", m.value)
        } else {
            format!("`{}`", m.value)
        };
        let _ = writeln!(
            out,
            "| {} | `{}` | {} |",
            value,
            m.name,
            cell(&summarize(&m.doc))
        );
    }
    let _ = writeln!(out);
}

fn emit_status_and_doc(out: &mut String, status: Status, doc: &str) {
    if status != Status::Unstated {
        let _ = writeln!(out, "{}\n", status_line(status, None));
    }
    if !doc.is_empty() {
        let _ = writeln!(out, "{doc}\n");
    }
}

// --- rendering helpers ---

/// The status sentence a reader needs before the prose: whether the thing
/// described exists here today.
fn status_line(status: Status, added: Option<u64>) -> String {
    let text = match status {
        Status::Implemented => "**Implemented.**",
        Status::Designed => "**Designed** — specified here, not yet built.",
        Status::Deferred => "**Deferred** — specified and explicitly not built.",
        Status::Unstated => "**Status unstated.**",
    };
    match added {
        Some(v) => format!("{text} Since interface version {v}."),
        None => text.to_owned(),
    }
}

/// The first paragraph of a doc comment, flattened to one line — what a table
/// cell can hold. The full prose is printed below the table.
fn summarize(doc: &str) -> String {
    let first: Vec<&str> = doc
        .lines()
        .map(str::trim)
        .take_while(|line| !line.is_empty())
        .collect();
    first.join(" ")
}

/// Escapes a value for a Markdown table cell. A `|` inside a code span still
/// splits the row — the ledger gate exists because eight rows lost their last
/// cell to exactly this — and a newline ends the table outright.
fn cell(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '|' => out.push_str("\\|"),
            '\n' | '\r' => out.push(' '),
            _ => out.push(c),
        }
    }
    if out.is_empty() {
        out.push('—');
    }
    out
}

/// A trailing clause, or nothing when there is no prose to add.
fn suffix(text: &str) -> String {
    if text.is_empty() {
        ".".to_owned()
    } else {
        format!(" — {text}")
    }
}

/// The heading anchor of a call's detail section, derived the way a
/// Markdown renderer derives one from `### \`Name\` — call N`: punctuation
/// dropped, spaces hyphenated, lowercased. Written out rather than guessed,
/// because a summary table of fifty broken links is worse than none.
fn anchor(name: &str, number: u64) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        }
    }
    // The two spaces around the em dash in the heading each become a hyphen.
    format!("{out}--call-{number}")
}

#[cfg(test)]
#[path = "tests/codegen_docs.rs"]
mod tests;
