// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Jagadeesh Chandra Muddana <mjchandra@gmail.com>

//! Fuzz-target generation for the frozen/ABI subset: a structure-aware target
//! per `@abi` struct, driven by `tessera-isl-fuzz`.
//!
//! `docs/lifecycle/02` ("Tier 2") asks for *"structure-aware fuzz targets
//! generated from ISL"*. The compiler is the only thing that knows what makes a
//! target structure-aware — every field's offset, width and legal domain — so
//! it emits three things a fuzzer cannot work out for itself:
//!
//! - the **layout**, so a mutation can name a field instead of a byte;
//! - the **domains**, so the engine knows which values must be accepted and
//!   which must be refused, which is what turns a crash-hunt into an oracle;
//! - a **seed record that decodes**, so mutation starts inside the type rather
//!   than outside it. A byte-level fuzzer has no way to construct one: the
//!   first strict-enum field refuses nearly everything, so it is still knocking
//!   on the door when its budget runs out.
//!
//! Output is byte-stable across rebuilds, like the Rust bindings, and is a
//! build output that is never committed.
//!
//! Normative: docs/lifecycle/02-build-and-test-infrastructure.md ("Tier 2"),
//! docs/api/03-interface-schema-language.md ("Generated Artifacts")

use crate::ast::PrimType;
use crate::ir::{Ir, IrDecl, IrFieldType, IrStruct};
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// A schema's strict enums, by name: their members and the width they occupy.
type EnumMap<'a> = BTreeMap<&'a str, (&'a Vec<(String, u64)>, PrimType)>;
/// A schema's `bits` declarations, by name: the union of every declared bit.
type BitsMap<'a> = BTreeMap<&'a str, u64>;
/// A schema's frozen structs, by name, so a nested one can be walked.
type StructMap<'a> = BTreeMap<&'a str, &'a IrStruct>;
/// One entry of a target's layout: name, offset, width, and the domain
/// expression the generated code carries.
type Layout = (String, usize, usize, String);

/// How many inputs each target gets in a pre-merge run.
///
/// Bounded because this is a tier-2 test inside a 30-minute pre-merge budget,
/// not the continuous fleet `docs/lifecycle/02` puts post-merge. The number is
/// here rather than in the generated test so raising it is a one-line change in
/// the compiler and applies everywhere at once.
const ITERATIONS: u32 = 2000;

/// The run's seed. Fixed, because a fuzz test that explored somewhere new on
/// every CI run would fail on unrelated changes and pass on the retry, which is
/// how a suite stops being believed. New ground comes from raising the
/// iteration count or changing this deliberately.
const SEED: u64 = 0x151_F022_9EED;

/// Emits a deterministic fuzz-target module for `ir`, importing the generated
/// bindings from `bindings_crate`.
pub fn emit(ir: &Ir, bindings_crate: &str) -> String {
    let enums: EnumMap<'_> = ir
        .decls
        .iter()
        .filter_map(|d| match d {
            IrDecl::Enum(e) => Some((e.name.as_str(), (&e.members, e.base))),
            _ => None,
        })
        .collect();
    let bits: BitsMap<'_> = ir
        .decls
        .iter()
        .filter_map(|d| match d {
            IrDecl::Bits(b) => Some((
                b.name.as_str(),
                b.members.iter().fold(0u64, |acc, (_, v)| acc | v),
            )),
            _ => None,
        })
        .collect();
    let structs: StructMap<'_> = ir
        .decls
        .iter()
        .filter_map(|d| match d {
            IrDecl::Struct(s) => Some((s.name.as_str(), s)),
            _ => None,
        })
        .collect();

    let mut out = String::new();
    out.push_str("// @generated by islc --fuzz — do not edit; regenerate from the schema.\n");
    let _ = writeln!(out, "// library {}", ir.library);
    out.push_str("#![allow(dead_code, unused_imports, non_upper_case_globals, clippy::all)]\n");
    let _ = writeln!(out, "use {bindings_crate}::*;");
    out.push_str("use tessera_isl_fuzz::{Domain, Field, Target, probe, run};\n\n");

    let abi: Vec<&IrStruct> = ir
        .decls
        .iter()
        .filter_map(|d| match d {
            IrDecl::Struct(s) if s.abi => Some(s),
            _ => None,
        })
        .collect();

    for s in &abi {
        let mut fields = Vec::new();
        let mut seed = vec![0u8; s.size];
        collect(s, 0, "", &enums, &bits, &structs, &mut fields, &mut seed);

        let _ = writeln!(out, "const F_{}: &[Field] = &[", s.name);
        for (name, offset, size, domain) in &fields {
            let _ = writeln!(
                out,
                "    Field {{ name: {name:?}, offset: {offset}, size: {size}, domain: {domain} }},"
            );
        }
        out.push_str("];\n");
        let _ = writeln!(out, "const S_{}: &[u8] = &{seed:?};", s.name);
    }

    out.push_str("\n/// Every `@abi` struct in this schema, as a fuzz target.\n");
    out.push_str("pub fn targets() -> Vec<Target> {\n    vec![\n");
    for s in &abi {
        let _ = writeln!(
            out,
            "        Target {{ name: {:?}, wire_size: {}, fields: F_{}, seed: S_{}, probe: probe::<{}> }},",
            s.name, s.size, s.name, s.name, s.name
        );
    }
    out.push_str("    ]\n}\n\n");

    // The test the build rule runs. Generated rather than hand-written per
    // schema so a new schema is fuzzed by existing, and a schema whose targets
    // stopped being generated fails to build rather than silently testing
    // nothing.
    out.push_str(
        "#[test]\n\
         fn every_frozen_struct_survives_the_oracle() {\n\
        \x20   let targets = targets();\n\
        \x20   assert!(!targets.is_empty(), \"a schema with no @abi struct has no decoder to fuzz\");\n",
    );
    let _ = writeln!(
        out,
        "    let (coverage, finding) = run(&targets, {ITERATIONS}, {SEED:#x});"
    );
    out.push_str(
        "    assert_eq!(finding, None, \"reproduce with the seed and iteration in the finding\");\n\
        \x20   // A run that only ever accepted, or only ever refused, exercised one\n\
        \x20   // half of the decoder and reported success for the other.\n\
        \x20   assert!(coverage.accepted > 0, \"nothing decoded: {coverage:?}\");\n\
        \x20   assert!(coverage.rejected > 0, \"nothing was refused: {coverage:?}\");\n\
         }\n",
    );
    out
}

/// Walks one struct's fields, appending layout entries and filling the seed.
///
/// `prefix` names a nested struct's fields as `outer.inner`, so a finding
/// points at a field rather than at an offset.
#[allow(clippy::too_many_arguments)]
fn collect(
    s: &IrStruct,
    base_offset: usize,
    prefix: &str,
    enums: &EnumMap<'_>,
    bits: &BitsMap<'_>,
    structs: &StructMap<'_>,
    fields: &mut Vec<Layout>,
    seed: &mut [u8],
) {
    for f in &s.fields {
        let offset = base_offset + f.offset;
        let name = if prefix.is_empty() {
            f.name.clone()
        } else {
            format!("{prefix}.{}", f.name)
        };
        match &f.ty {
            IrFieldType::Enum { name: ty, .. } => {
                let members = enums.get(ty.as_str()).map(|(m, _)| *m);
                let values: Vec<u64> = members
                    .map(|m| m.iter().map(|(_, v)| *v).collect())
                    .unwrap_or_default();
                let list = values
                    .iter()
                    .map(|v| format!("{v}"))
                    .collect::<Vec<_>>()
                    .join(", ");
                fields.push((name, offset, f.size, format!("Domain::Enum(&[{list}])")));
                // A member the schema declares, so the seed decodes.
                write_le(seed, offset, f.size, values.first().copied().unwrap_or(0));
            }
            IrFieldType::Bits { name: ty, .. } => {
                let known = bits.get(ty.as_str()).copied().unwrap_or(0);
                fields.push((name, offset, f.size, format!("Domain::Mask({known:#x})")));
                // The empty subset, which every `bits` accepts.
            }
            IrFieldType::Prim(PrimType::Bool) => {
                fields.push((name, offset, f.size, "Domain::Enum(&[0, 1])".into()));
            }
            IrFieldType::Prim(_) | IrFieldType::Handle { .. } => {
                fields.push((name, offset, f.size, "Domain::Any".into()));
            }
            IrFieldType::Struct { name: ty } => {
                if let Some(nested) = structs.get(ty.as_str()) {
                    collect(nested, offset, &name, enums, bits, structs, fields, seed);
                }
            }
            // An array of bytes is a run of unconstrained values; bit flips
            // reach it and there is no domain to aim at. Arrays of anything
            // narrower than a byte do not occur in the frozen subset.
            IrFieldType::Array { .. } => {}
            // Out-of-line types are not legal in a frozen struct.
            IrFieldType::String { .. } | IrFieldType::Vector { .. } => {}
        }
    }
}

fn write_le(buf: &mut [u8], offset: usize, size: usize, value: u64) {
    let bytes = value.to_le_bytes();
    for (i, byte) in bytes.iter().take(size.min(8)).enumerate() {
        if let Some(slot) = buf.get_mut(offset + i) {
            *slot = *byte;
        }
    }
}
