// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Jagadeesh Chandra Muddana <mjchandra@gmail.com>

//! Rust binding generation for the frozen/ABI subset: deterministic Rust
//! source (types plus a canonical encode/decode/validate implementation)
//! targeting the `tessera-isl-runtime` codec. Emits bits, enums, frozen
//! structs, unions (strict and flexible), tables, the bounded collections
//! `string:N`/`vector<T>:N`, and protocols (interface id, method ordinals, and
//! typed request/response/event dispatch enums). A nested `table`/`union` field
//! is the one remaining `compile_error!` deferral (D10).
//!
//! Output is byte-stable across rebuilds — declaration order is preserved and
//! nothing environment-derived is emitted — so an independent rebuild is
//! bit-for-bit identical. Generated code is a build output, never committed.
//!
//! Normative: docs/api/03-interface-schema-language.md ("Generated Artifacts",
//! "Wire Format")

use crate::ast::PrimType;
use crate::ir::{
    Ir, IrBits, IrDecl, IrEnum, IrFieldType, IrMethodKind, IrOrdinalMember, IrPayload, IrProtocol,
    IrStruct, IrUnion,
};
use std::collections::BTreeMap;
use std::fmt::Write as _;

const RT: &str = "tessera_isl_runtime";

/// Emits deterministic Rust bindings for `ir`.
pub fn emit(ir: &Ir) -> String {
    // Struct (size, align) map, so a union variant that is a nested struct
    // can be given its compile-time wire size — the same map the IR layout
    // pass uses (`IrFieldType::size`).
    let structs: BTreeMap<String, (usize, usize)> = ir
        .decls
        .iter()
        .filter_map(|d| match d {
            IrDecl::Struct(s) => Some((s.name.clone(), (s.size, s.align))),
            _ => None,
        })
        .collect();

    let mut out = String::new();
    out.push_str("// @generated by islc — do not edit; regenerate from the schema.\n");
    let _ = writeln!(out, "// library {}", ir.library);
    // The import set depends on schema shape (a schema with no handle fields
    // never names `HandleRef`; one with only deferred decls uses none of the
    // codec traits), so generated code is exempt from the unused-import lint —
    // as it is from dead_code for unused structs.
    out.push_str("#![allow(dead_code, unused_imports, non_upper_case_globals, clippy::all)]\n");
    // Bindings are `no_std` so the same crate serves host services and the
    // `no_std` kernel ABI (the runtime codec is `no_std` too). The cargo inner
    // loop that `include!`s this file into a `no_std` crate strips the inner
    // attributes (kernel/kcore/build.rs); Bazel compiles it as a crate root,
    // where `#![no_std]` lets it link into the bare-metal kernel.
    out.push_str("#![no_std]\n");
    let _ = writeln!(
        out,
        "use {RT}::{{Reader, Writer, WireEncode, WireDecode, WireError, HandleRef, BoundedString, BoundedVec}};\n"
    );
    for decl in &ir.decls {
        match decl {
            IrDecl::Bits(b) => emit_bits(&mut out, b),
            IrDecl::Enum(e) => emit_enum(&mut out, e),
            IrDecl::Struct(s) => emit_struct(&mut out, s),
            IrDecl::Table(t) => emit_table(&mut out, t, &structs),
            IrDecl::Union(u) => emit_union(&mut out, u, &structs),
            IrDecl::Protocol(p) => emit_protocol(&mut out, p),
        }
    }
    out
}

fn emit_bits(out: &mut String, b: &IrBits) {
    let base = rust_prim(b.base);
    let write = write_method(b.base);
    let read = read_method(b.base);
    let known: u64 = b.members.iter().fold(0, |acc, (_, v)| acc | v);
    let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Eq, Debug)]");
    let _ = writeln!(out, "pub struct {}(pub {base});", b.name);
    let _ = writeln!(out, "impl {} {{", b.name);
    for (name, value) in &b.members {
        let _ = writeln!(
            out,
            "    pub const {name}: {} = {}({value:#x});",
            b.name, b.name
        );
    }
    let _ = writeln!(out, "    pub const KNOWN_BITS: {base} = {known:#x};");
    let _ = writeln!(out, "    pub const fn bits(self) -> {base} {{ self.0 }}");
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "impl WireEncode for {} {{", b.name);
    let _ = writeln!(
        out,
        "    fn encode(&self, w: &mut Writer<'_>) -> Result<(), WireError> {{ w.{write}(self.0) }}"
    );
    let _ = writeln!(
        out,
        "    fn encoded_len(&self) -> usize {{ {} }}",
        b.base.size()
    );
    let _ = writeln!(out, "}}");
    let _ = writeln!(out, "impl WireDecode for {} {{", b.name);
    let _ = writeln!(
        out,
        "    fn decode(r: &mut Reader<'_>) -> Result<Self, WireError> {{"
    );
    let _ = writeln!(out, "        let v = r.{read}()?;");
    let _ = writeln!(
        out,
        "        if v & !Self::KNOWN_BITS != 0 {{ return Err(WireError::BadBits); }}"
    );
    let _ = writeln!(out, "        Ok({}(v))", b.name);
    let _ = writeln!(out, "    }}\n}}\n");
}

fn emit_enum(out: &mut String, e: &IrEnum) {
    let base = rust_prim(e.base);
    let write = write_method(e.base);
    let read = read_method(e.base);
    if e.strict {
        let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Eq, Debug)]");
        let _ = writeln!(out, "#[repr({base})]");
        let _ = writeln!(out, "pub enum {} {{", e.name);
        for (name, value) in &e.members {
            let _ = writeln!(out, "    {} = {value},", to_camel(name));
        }
        let _ = writeln!(out, "}}");
        let _ = writeln!(out, "impl WireEncode for {} {{", e.name);
        let _ = writeln!(
            out,
            "    fn encode(&self, w: &mut Writer<'_>) -> Result<(), WireError> {{ w.{write}(*self as {base}) }}"
        );
        let _ = writeln!(
            out,
            "    fn encoded_len(&self) -> usize {{ {} }}",
            e.base.size()
        );
        let _ = writeln!(out, "}}");
        let _ = writeln!(out, "impl WireDecode for {} {{", e.name);
        let _ = writeln!(
            out,
            "    fn decode(r: &mut Reader<'_>) -> Result<Self, WireError> {{"
        );
        let _ = writeln!(out, "        match r.{read}()? {{");
        for (name, value) in &e.members {
            let _ = writeln!(out, "            {value} => Ok(Self::{}),", to_camel(name));
        }
        let _ = writeln!(out, "            _ => Err(WireError::BadEnum),");
        let _ = writeln!(out, "        }}\n    }}\n}}\n");
    } else {
        // Flexible enum: a newtype that preserves unknown values.
        let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Eq, Debug)]");
        let _ = writeln!(out, "pub struct {}(pub {base});", e.name);
        let _ = writeln!(out, "impl {} {{", e.name);
        for (name, value) in &e.members {
            let _ = writeln!(
                out,
                "    pub const {}: {} = {}({value});",
                name, e.name, e.name
            );
        }
        let _ = writeln!(out, "}}");
        let _ = writeln!(out, "impl WireEncode for {} {{", e.name);
        let _ = writeln!(
            out,
            "    fn encode(&self, w: &mut Writer<'_>) -> Result<(), WireError> {{ w.{write}(self.0) }}"
        );
        let _ = writeln!(
            out,
            "    fn encoded_len(&self) -> usize {{ {} }}",
            e.base.size()
        );
        let _ = writeln!(out, "}}");
        let _ = writeln!(out, "impl WireDecode for {} {{", e.name);
        let _ = writeln!(
            out,
            "    fn decode(r: &mut Reader<'_>) -> Result<Self, WireError> {{ Ok({}(r.{read}()?)) }}",
            e.name
        );
        let _ = writeln!(out, "}}\n");
    }
}

/// A union member that carries a wire-encodable inline type (reserved slots
/// and — until the tables milestone — out-of-line variants are handled
/// separately).
struct Variant<'a> {
    ordinal: u64,
    /// CamelCase Rust variant name, from the member's field name.
    camel: String,
    ty: &'a IrFieldType,
    /// Compile-time wire size of the payload.
    size: usize,
}

fn emit_union(out: &mut String, u: &IrUnion, structs: &BTreeMap<String, (usize, usize)>) {
    // An out-of-line variant (string/vector/nested table/union) has no inline
    // type, so `member_field_type` left `ty = None` with a name present. Its
    // wire codegen rides with the tables milestone; emit a loud `compile_error!`
    // rather than a silently-incomplete union.
    for m in &u.members {
        if m.field.is_some() && m.ty.is_none() {
            let field = m.field.as_deref().unwrap_or("?");
            let _ = writeln!(
                out,
                "compile_error!(\"union {} variant `{field}` (ordinal {}): out-of-line variant wire codegen deferred (D10)\");\n",
                u.name, m.ordinal
            );
            return;
        }
    }

    let variants: Vec<Variant<'_>> = u
        .members
        .iter()
        .filter_map(|m: &IrOrdinalMember| {
            let (name, ty) = (m.field.as_ref()?, m.ty.as_ref()?);
            Some(Variant {
                ordinal: m.ordinal,
                camel: to_camel(name),
                ty,
                size: ty.size(structs),
            })
        })
        .collect();

    // Type definition. Every variant is a single-field tuple variant; a
    // flexible union additionally preserves an unknown ordinal's payload in a
    // bounded buffer sized by the largest *known* variant (a future variant
    // larger than this decodes as `BoundExceeded`, never silently truncated).
    let max_payload = variants.iter().map(|v| v.size).max().unwrap_or(0);
    let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Debug)]");
    let _ = writeln!(out, "pub enum {} {{", u.name);
    for v in &variants {
        let _ = writeln!(out, "    {}({}),", v.camel, rust_type(v.ty));
    }
    if !u.strict {
        let _ = writeln!(
            out,
            "    Unknown {{ ordinal: u32, len: u32, bytes: [u8; {max_payload}] }},"
        );
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(
        out,
        "impl {} {{ pub const MAX_PAYLOAD: usize = {max_payload}; }}",
        u.name
    );

    // encode: ordinal (u32) + size (u32) + payload.
    let _ = writeln!(out, "impl WireEncode for {} {{", u.name);
    let _ = writeln!(
        out,
        "    fn encode(&self, w: &mut Writer<'_>) -> Result<(), WireError> {{"
    );
    let _ = writeln!(out, "        match self {{");
    for v in &variants {
        let _ = writeln!(out, "            Self::{}(val) => {{", v.camel);
        let _ = writeln!(out, "                w.write_u32({})?;", v.ordinal);
        if v.ty.is_bounded_collection() {
            let _ = writeln!(
                out,
                "                w.write_u32(val.encoded_len() as u32)?;"
            );
        } else {
            let _ = writeln!(out, "                w.write_u32({})?;", v.size);
        }
        emit_value_encode(out, v.ty);
        let _ = writeln!(out, "                Ok(())");
        let _ = writeln!(out, "            }}");
    }
    if !u.strict {
        let _ = writeln!(
            out,
            "            Self::Unknown {{ ordinal, len, bytes }} => {{"
        );
        let _ = writeln!(out, "                w.write_u32(*ordinal)?;");
        let _ = writeln!(out, "                w.write_u32(*len)?;");
        let _ = writeln!(
            out,
            "                for b in &bytes[..*len as usize] {{ w.write_u8(*b)?; }}"
        );
        let _ = writeln!(out, "                Ok(())");
        let _ = writeln!(out, "            }}");
    }
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    fn encoded_len(&self) -> usize {{");
    let _ = writeln!(out, "        8 + match self {{");
    for v in &variants {
        if v.ty.is_bounded_collection() {
            let _ = writeln!(
                out,
                "            Self::{}(val) => val.encoded_len(),",
                v.camel
            );
        } else {
            let _ = writeln!(out, "            Self::{}(_) => {},", v.camel, v.size);
        }
    }
    if !u.strict {
        let _ = writeln!(
            out,
            "            Self::Unknown {{ len, .. }} => *len as usize,"
        );
    }
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");

    // decode: read the envelope, decode the payload from a sub-reader whose
    // `finish` enforces that the declared size was minimal.
    let _ = writeln!(out, "impl WireDecode for {} {{", u.name);
    let _ = writeln!(
        out,
        "    fn decode(r: &mut Reader<'_>) -> Result<Self, WireError> {{"
    );
    let _ = writeln!(out, "        let ordinal = r.read_u32()?;");
    let _ = writeln!(out, "        let size = r.read_u32()? as usize;");
    let _ = writeln!(out, "        let payload = r.take(size)?;");
    let _ = writeln!(out, "        let mut sr = Reader::new(payload);");
    let _ = writeln!(out, "        match ordinal {{");
    for v in &variants {
        let _ = writeln!(out, "            {} => {{", v.ordinal);
        emit_value_decode(out, v.ty);
        let _ = writeln!(out, "                sr.finish()?;");
        let _ = writeln!(out, "                Ok(Self::{}(val))", v.camel);
        let _ = writeln!(out, "            }}");
    }
    if u.strict {
        let _ = writeln!(out, "            _ => Err(WireError::BadUnionTag),");
    } else {
        let _ = writeln!(out, "            other => {{");
        let _ = writeln!(
            out,
            "                if size > Self::MAX_PAYLOAD {{ return Err(WireError::BoundExceeded); }}"
        );
        let _ = writeln!(out, "                let mut bytes = [0u8; {max_payload}];");
        let _ = writeln!(
            out,
            "                bytes[..size].copy_from_slice(payload);"
        );
        let _ = writeln!(
            out,
            "                Ok(Self::Unknown {{ ordinal: other, len: size as u32, bytes }})"
        );
        let _ = writeln!(out, "            }}");
    }
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}\n}}\n");
}

/// A table field that carries a wire-encodable inline type (reserved slots and
/// out-of-line fields are handled separately).
struct TableField<'a> {
    ordinal: u64,
    name: &'a str,
    ty: &'a IrFieldType,
    size: usize,
}

fn emit_table(
    out: &mut String,
    t: &crate::ir::IrTable,
    structs: &BTreeMap<String, (usize, usize)>,
) {
    // An out-of-line field (string/vector/nested table/union) has no inline
    // type; its wire codegen rides with the string/vector follow-up. Emit a
    // loud `compile_error!` rather than a silently-incomplete table.
    for m in &t.members {
        if m.field.is_some() && m.ty.is_none() {
            let field = m.field.as_deref().unwrap_or("?");
            let _ = writeln!(
                out,
                "compile_error!(\"table {} field `{field}` (ordinal {}): out-of-line field wire codegen deferred (D10)\");\n",
                t.name, m.ordinal
            );
            return;
        }
    }

    // Fields in ascending ordinal order — the canonical wire order. The schema
    // usually declares them ascending already, but sorting makes the emitter
    // independent of declaration order.
    let mut fields: Vec<TableField<'_>> = t
        .members
        .iter()
        .filter_map(|m| {
            let (name, ty) = (m.field.as_deref()?, m.ty.as_ref()?);
            Some(TableField {
                ordinal: m.ordinal,
                name,
                ty,
                size: ty.size(structs),
            })
        })
        .collect();
    fields.sort_by_key(|f| f.ordinal);

    // A table is a bag of optional fields: every field is `Option<T>`, and the
    // all-absent value is `Default`.
    let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Debug, Default)]");
    let _ = writeln!(out, "pub struct {} {{", t.name);
    for f in &fields {
        let _ = writeln!(out, "    pub {}: Option<{}>,", f.name, rust_type(f.ty));
    }
    let _ = writeln!(out, "}}");

    // encode: count of present fields, then one envelope per present field in
    // ascending ordinal order.
    let _ = writeln!(out, "impl WireEncode for {} {{", t.name);
    let _ = writeln!(
        out,
        "    fn encode(&self, w: &mut Writer<'_>) -> Result<(), WireError> {{"
    );
    if fields.is_empty() {
        let _ = writeln!(out, "        w.write_u32(0)?;");
    } else {
        let count_terms: Vec<String> = fields
            .iter()
            .map(|f| format!("self.{}.is_some() as u32", f.name))
            .collect();
        let _ = writeln!(out, "        let count = {};", count_terms.join(" + "));
        let _ = writeln!(out, "        w.write_u32(count)?;");
        for f in &fields {
            let _ = writeln!(out, "        if let Some(val) = &self.{} {{", f.name);
            let _ = writeln!(out, "            w.write_u32({})?;", f.ordinal);
            // A bounded field's size varies with its content, so it is read
            // from the value; an inline field's is a compile-time constant.
            if f.ty.is_bounded_collection() {
                let _ = writeln!(out, "            w.write_u32(val.encoded_len() as u32)?;");
            } else {
                let _ = writeln!(out, "            w.write_u32({})?;", f.size);
            }
            emit_value_encode(out, f.ty);
            let _ = writeln!(out, "        }}");
        }
    }
    let _ = writeln!(out, "        Ok(())");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    fn encoded_len(&self) -> usize {{");
    let _ = writeln!(out, "        let mut n = 4;");
    for f in &fields {
        if f.ty.is_bounded_collection() {
            let _ = writeln!(
                out,
                "        if let Some(val) = &self.{} {{ n += 8 + val.encoded_len(); }}",
                f.name
            );
        } else {
            let _ = writeln!(
                out,
                "        if self.{}.is_some() {{ n += {}; }}",
                f.name,
                8 + f.size
            );
        }
    }
    let _ = writeln!(out, "        n");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");

    // decode: fields default to absent; each present envelope must be strictly
    // ascending by ordinal (canonical), and an unknown ordinal is skipped.
    let _ = writeln!(out, "impl WireDecode for {} {{", t.name);
    let _ = writeln!(
        out,
        "    fn decode(r: &mut Reader<'_>) -> Result<Self, WireError> {{"
    );
    let _ = writeln!(out, "        let mut out = Self::default();");
    let _ = writeln!(out, "        let count = r.read_u32()?;");
    let _ = writeln!(out, "        let mut prev: i64 = -1;");
    let _ = writeln!(out, "        for _ in 0..count {{");
    let _ = writeln!(out, "            let ordinal = r.read_u32()?;");
    let _ = writeln!(
        out,
        "            if ordinal as i64 <= prev {{ return Err(WireError::NonCanonicalTable); }}"
    );
    let _ = writeln!(out, "            prev = ordinal as i64;");
    let _ = writeln!(out, "            let size = r.read_u32()? as usize;");
    let _ = writeln!(out, "            match ordinal {{");
    for f in &fields {
        let _ = writeln!(out, "                {} => {{", f.ordinal);
        let _ = writeln!(out, "                    let payload = r.take(size)?;");
        let _ = writeln!(
            out,
            "                    let mut sr = Reader::new(payload);"
        );
        emit_value_decode(out, f.ty);
        let _ = writeln!(out, "                    sr.finish()?;");
        let _ = writeln!(out, "                    out.{} = Some(val);", f.name);
        let _ = writeln!(out, "                }}");
    }
    // Unknown ordinal: consume its bytes and discard (forward compatibility).
    let _ = writeln!(out, "                _ => {{ r.take(size)?; }}");
    let _ = writeln!(out, "            }}");
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "        Ok(out)");
    let _ = writeln!(out, "    }}\n}}\n");
}

/// Emits the payload write for a value bound as `val` (a shared reference),
/// into writer `w` — a union variant or a present table field.
fn emit_value_encode(out: &mut String, ty: &IrFieldType) {
    match ty {
        IrFieldType::Prim(p) => {
            let _ = writeln!(out, "                w.{}(*val)?;", write_method(*p));
        }
        IrFieldType::Handle => {
            let _ = writeln!(out, "                w.write_handle(*val)?;");
        }
        IrFieldType::Enum { .. }
        | IrFieldType::Bits { .. }
        | IrFieldType::Struct { .. }
        | IrFieldType::String { .. }
        | IrFieldType::Vector { .. } => {
            // Each of these is a `WireEncode` type (a generated struct/enum/bits
            // or a runtime `BoundedString`/`BoundedVec`).
            let _ = writeln!(out, "                val.encode(w)?;");
        }
        IrFieldType::Array { elem, .. } => match elem.as_ref() {
            IrFieldType::Prim(p) => {
                let _ = writeln!(
                    out,
                    "                for e in val {{ w.{}(*e)?; }}",
                    write_method(*p)
                );
            }
            _ => {
                let _ = writeln!(out, "                for e in val {{ e.encode(w)?; }}");
            }
        },
    }
}

/// Emits the payload decode for a union variant, binding the result as `val`,
/// reading from sub-reader `sr`.
fn emit_value_decode(out: &mut String, ty: &IrFieldType) {
    match ty {
        IrFieldType::Prim(p) => {
            let _ = writeln!(out, "                let val = sr.{}()?;", read_method(*p));
        }
        IrFieldType::Handle => {
            let _ = writeln!(out, "                let val = sr.read_handle()?;");
        }
        IrFieldType::Enum { name: tn, .. }
        | IrFieldType::Bits { name: tn, .. }
        | IrFieldType::Struct { name: tn } => {
            let _ = writeln!(out, "                let val = {tn}::decode(&mut sr)?;");
        }
        // A bounded collection decodes through its `WireDecode` impl; the
        // fully-qualified form works for the generic `BoundedString<N>` /
        // `BoundedVec<T, N>` types.
        IrFieldType::String { .. } | IrFieldType::Vector { .. } => {
            let _ = writeln!(
                out,
                "                let val = <{} as WireDecode>::decode(&mut sr)?;",
                rust_type(ty)
            );
        }
        IrFieldType::Array { elem, len } => match elem.as_ref() {
            IrFieldType::Prim(p) => {
                let _ = writeln!(
                    out,
                    "                let mut val = [{}; {len}];",
                    prim_default(*p)
                );
                let _ = writeln!(
                    out,
                    "                for slot in &mut val {{ *slot = sr.{}()?; }}",
                    read_method(*p)
                );
            }
            other => {
                let elem_ty = rust_type(other);
                let _ = writeln!(
                    out,
                    "                let mut val: [{elem_ty}; {len}] = [Default::default(); {len}];"
                );
                let _ = writeln!(
                    out,
                    "                for slot in &mut val {{ *slot = {elem_ty}::decode(&mut sr)?; }}"
                );
            }
        },
    }
}

fn emit_struct(out: &mut String, s: &IrStruct) {
    let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Debug)]");
    let _ = writeln!(out, "pub struct {} {{", s.name);
    for f in &s.fields {
        let _ = writeln!(out, "    pub {}: {},", f.name, rust_type(&f.ty));
    }
    let _ = writeln!(out, "}}");
    let _ = writeln!(
        out,
        "impl {} {{ pub const WIRE_SIZE: usize = {}; }}",
        s.name, s.size
    );

    // encode
    let _ = writeln!(out, "impl WireEncode for {} {{", s.name);
    let _ = writeln!(
        out,
        "    fn encode(&self, w: &mut Writer<'_>) -> Result<(), WireError> {{"
    );
    let mut cursor = 0usize;
    for f in &s.fields {
        if f.offset > cursor {
            let _ = writeln!(out, "        w.write_zeros({})?;", f.offset - cursor);
        }
        emit_encode_field(out, f);
        cursor = f.offset + f.size;
    }
    if s.size > cursor {
        let _ = writeln!(out, "        w.write_zeros({})?;", s.size - cursor);
    }
    let _ = writeln!(out, "        Ok(())");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "    fn encoded_len(&self) -> usize {{ {} }}", s.size);
    let _ = writeln!(out, "}}");

    // decode
    let _ = writeln!(out, "impl WireDecode for {} {{", s.name);
    let _ = writeln!(
        out,
        "    fn decode(r: &mut Reader<'_>) -> Result<Self, WireError> {{"
    );
    let mut cursor = 0usize;
    for f in &s.fields {
        if f.offset > cursor {
            let _ = writeln!(out, "        r.expect_zeros({})?;", f.offset - cursor);
        }
        emit_decode_field(out, f);
        cursor = f.offset + f.size;
    }
    if s.size > cursor {
        let _ = writeln!(out, "        r.expect_zeros({})?;", s.size - cursor);
    }
    let _ = writeln!(out, "        Ok(Self {{");
    for f in &s.fields {
        let _ = writeln!(out, "            {},", f.name);
    }
    let _ = writeln!(out, "        }})");
    let _ = writeln!(out, "    }}\n}}\n");
}

fn emit_encode_field(out: &mut String, f: &crate::ir::IrField) {
    let name = &f.name;
    match &f.ty {
        IrFieldType::Prim(p) => {
            let _ = writeln!(out, "        w.{}(self.{name})?;", write_method(*p));
        }
        IrFieldType::Handle => {
            let _ = writeln!(out, "        w.write_handle(self.{name})?;");
        }
        IrFieldType::Enum { .. } | IrFieldType::Bits { .. } | IrFieldType::Struct { .. } => {
            let _ = writeln!(out, "        self.{name}.encode(w)?;");
        }
        IrFieldType::Array { elem, .. } => match elem.as_ref() {
            IrFieldType::Prim(p) => {
                let _ = writeln!(
                    out,
                    "        for v in &self.{name} {{ w.{}(*v)?; }}",
                    write_method(*p)
                );
            }
            _ => {
                let _ = writeln!(out, "        for v in &self.{name} {{ v.encode(w)?; }}");
            }
        },
        // Structs are the frozen inline subset; the checker rejects
        // string/vector fields, so these never reach struct codegen.
        IrFieldType::String { .. } | IrFieldType::Vector { .. } => {
            unreachable!("frozen struct fields are inline (checked in check.rs)")
        }
    }
}

fn emit_decode_field(out: &mut String, f: &crate::ir::IrField) {
    let name = &f.name;
    match &f.ty {
        IrFieldType::Prim(p) => {
            let _ = writeln!(out, "        let {name} = r.{}()?;", read_method(*p));
        }
        IrFieldType::Handle => {
            let _ = writeln!(out, "        let {name} = r.read_handle()?;");
        }
        IrFieldType::Enum { name: tn, .. }
        | IrFieldType::Bits { name: tn, .. }
        | IrFieldType::Struct { name: tn } => {
            let _ = writeln!(out, "        let {name} = {tn}::decode(r)?;");
        }
        IrFieldType::Array { elem, len } => match elem.as_ref() {
            IrFieldType::Prim(p) => {
                let _ = writeln!(
                    out,
                    "        let mut {name} = [{}; {len}];",
                    prim_default(*p)
                );
                let _ = writeln!(
                    out,
                    "        for slot in &mut {name} {{ *slot = r.{}()?; }}",
                    read_method(*p)
                );
            }
            other => {
                let elem_ty = rust_type(other);
                let _ = writeln!(
                    out,
                    "        let mut {name}_vec: [{elem_ty}; {len}] = [Default::default(); {len}];"
                );
                let _ = writeln!(
                    out,
                    "        for slot in &mut {name}_vec {{ *slot = {elem_ty}::decode(r)?; }}"
                );
                let _ = writeln!(out, "        let {name} = {name}_vec;");
            }
        },
        // As in `emit_encode_field`: unreachable for a frozen struct.
        IrFieldType::String { .. } | IrFieldType::Vector { .. } => {
            unreachable!("frozen struct fields are inline (checked in check.rs)")
        }
    }
}

fn rust_type(ft: &IrFieldType) -> String {
    match ft {
        IrFieldType::Prim(p) => rust_prim(*p).to_owned(),
        IrFieldType::Enum { name, .. }
        | IrFieldType::Bits { name, .. }
        | IrFieldType::Struct { name } => name.clone(),
        IrFieldType::Handle => "HandleRef".to_owned(),
        IrFieldType::Array { elem, len } => format!("[{}; {len}]", rust_type(elem)),
        IrFieldType::String { max } => format!("BoundedString<{max}>"),
        IrFieldType::Vector { elem, max } => {
            format!("BoundedVec<{}, {max}>", rust_type(elem))
        }
    }
}

fn rust_prim(p: PrimType) -> &'static str {
    match p {
        PrimType::Bool => "bool",
        PrimType::Int8 => "i8",
        PrimType::Int16 => "i16",
        PrimType::Int32 => "i32",
        PrimType::Int64 => "i64",
        PrimType::Uint8 => "u8",
        PrimType::Uint16 => "u16",
        PrimType::Uint32 => "u32",
        PrimType::Uint64 => "u64",
        PrimType::Float32 => "f32",
        PrimType::Float64 => "f64",
    }
}

fn prim_default(p: PrimType) -> &'static str {
    match p {
        PrimType::Bool => "false",
        PrimType::Float32 | PrimType::Float64 => "0.0",
        _ => "0",
    }
}

fn write_method(p: PrimType) -> String {
    match p {
        PrimType::Bool => "write_bool".to_owned(),
        _ => format!("write_{}", rust_prim(p)),
    }
}

fn read_method(p: PrimType) -> String {
    match p {
        PrimType::Bool => "read_bool".to_owned(),
        _ => format!("read_{}", rust_prim(p)),
    }
}

/// Converts an `UPPER_SNAKE` enum member name to a `CamelCase` Rust variant.
fn to_camel(name: &str) -> String {
    let mut out = String::new();
    for part in name.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.extend(first.to_uppercase());
            out.extend(chars.map(|c| c.to_ascii_lowercase()));
        }
    }
    out
}

/// Converts a `CamelCase` method name to an `UPPER_SNAKE` const name
/// (`OnHeartbeat` → `ON_HEARTBEAT`).
fn to_upper_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_ascii_uppercase() && i > 0 {
            out.push('_');
        }
        out.extend(c.to_uppercase());
    }
    out
}

/// One arm of a dispatch enum: the variant name (the method name, already a
/// valid CamelCase identifier), its ordinal const name, and its payload.
struct Dispatch<'a> {
    variant: &'a str,
    method_const: String,
    payload: &'a IrPayload,
}

fn emit_protocol(out: &mut String, p: &IrProtocol) {
    // Namespace: the interface id and one ordinal const per method. The
    // channel `MessageHeader` (interface_id/method_id) is a separate generated
    // struct; a protocol binding is the payload layer keyed by these.
    let _ = writeln!(out, "pub struct {};", p.name);
    let _ = writeln!(out, "impl {} {{", p.name);
    let _ = writeln!(
        out,
        "    pub const INTERFACE_ID: u64 = {:#018x};",
        p.interface_id
    );
    for m in &p.methods {
        if matches!(m.kind, IrMethodKind::Reserved) {
            continue;
        }
        let _ = writeln!(
            out,
            "    pub const {}: u32 = {};",
            to_upper_snake(&m.name),
            m.ordinal
        );
    }
    let _ = writeln!(out, "}}");

    // Sort methods into the three dispatch directions.
    let mut incoming: Vec<Dispatch<'_>> = Vec::new();
    let mut outgoing: Vec<Dispatch<'_>> = Vec::new();
    let mut events: Vec<Dispatch<'_>> = Vec::new();
    for m in &p.methods {
        let mc = to_upper_snake(&m.name);
        match &m.kind {
            IrMethodKind::Call { request, response } => {
                incoming.push(Dispatch {
                    variant: &m.name,
                    method_const: mc.clone(),
                    payload: request,
                });
                outgoing.push(Dispatch {
                    variant: &m.name,
                    method_const: mc,
                    payload: response,
                });
            }
            IrMethodKind::OneWay { request } => incoming.push(Dispatch {
                variant: &m.name,
                method_const: mc,
                payload: request,
            }),
            IrMethodKind::Event { payload } => events.push(Dispatch {
                variant: &m.name,
                method_const: mc,
                payload,
            }),
            IrMethodKind::Reserved => {}
        }
    }

    emit_dispatch_enum(out, &p.name, &format!("{}Incoming", p.name), &incoming);
    emit_dispatch_enum(out, &p.name, &format!("{}Outgoing", p.name), &outgoing);
    emit_dispatch_enum(out, &p.name, &format!("{}Event", p.name), &events);
}

/// Emits a `{Proto}{Direction}` dispatch enum: a typed variant per method,
/// with `method_id`/`encode`/`decode` keyed by the method ordinal. A payload
/// variant carries its type; an empty payload is a unit variant that frames
/// zero bytes. Skipped entirely when the direction has no methods.
fn emit_dispatch_enum(out: &mut String, protocol: &str, enum_name: &str, arms: &[Dispatch<'_>]) {
    if arms.is_empty() {
        return;
    }
    let _ = writeln!(out, "#[derive(Clone, PartialEq, Debug)]");
    let _ = writeln!(out, "pub enum {enum_name} {{");
    for a in arms {
        match a.payload.type_name() {
            Some(ty) => {
                let _ = writeln!(out, "    {}({ty}),", a.variant);
            }
            None => {
                let _ = writeln!(out, "    {},", a.variant);
            }
        }
    }
    let _ = writeln!(out, "}}");

    let _ = writeln!(out, "impl {enum_name} {{");

    // method_id
    let _ = writeln!(out, "    pub fn method_id(&self) -> u32 {{");
    let _ = writeln!(out, "        match self {{");
    for a in arms {
        let bind = if a.payload.type_name().is_some() {
            "(_)"
        } else {
            ""
        };
        let _ = writeln!(
            out,
            "            Self::{}{bind} => {protocol}::{},",
            a.variant, a.method_const
        );
    }
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");

    // encode: the payload's own encoding, or nothing for an empty body.
    let _ = writeln!(
        out,
        "    pub fn encode(&self, w: &mut Writer<'_>) -> Result<(), WireError> {{"
    );
    let _ = writeln!(out, "        match self {{");
    for a in arms {
        if a.payload.type_name().is_some() {
            let _ = writeln!(out, "            Self::{}(v) => v.encode(w),", a.variant);
        } else {
            let _ = writeln!(out, "            Self::{} => Ok(()),", a.variant);
        }
    }
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}");

    // decode: dispatch by method ordinal; an unknown one is UnknownMethod.
    let _ = writeln!(
        out,
        "    pub fn decode(method_id: u32, r: &mut Reader<'_>) -> Result<Self, WireError> {{"
    );
    let _ = writeln!(out, "        match method_id {{");
    for a in arms {
        match a.payload.type_name() {
            Some(ty) => {
                let _ = writeln!(
                    out,
                    "            {protocol}::{} => Ok(Self::{}({ty}::decode(r)?)),",
                    a.method_const, a.variant
                );
            }
            None => {
                let _ = writeln!(
                    out,
                    "            {protocol}::{} => Ok(Self::{}),",
                    a.method_const, a.variant
                );
            }
        }
    }
    let _ = writeln!(out, "            _ => Err(WireError::UnknownMethod),");
    let _ = writeln!(out, "        }}");
    let _ = writeln!(out, "    }}\n}}\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compile;

    #[test]
    fn generated_source_is_deterministic() {
        let (ir, diags) = compile(include_str!("../examples/syscall_handle_ops.isl"));
        assert!(!diags.has_errors(), "{diags:?}");
        let ir = ir.expect("ir");
        assert_eq!(emit(&ir), emit(&ir));
    }

    #[test]
    fn emits_expected_shapes() {
        let (ir, _) = compile(include_str!("../examples/syscall_handle_ops.isl"));
        let src = emit(&ir.expect("ir"));
        assert!(src.contains("pub struct Rights(pub u64);"));
        assert!(src.contains("pub enum ObjectType"));
        assert!(src.contains("pub struct DuplicateArgs"));
        assert!(src.contains("pub source: HandleRef,"));
        assert!(src.contains("pub reserved: [u8; 4],"));
        assert!(src.contains("const WIRE_SIZE: usize = 40;"));
    }

    #[test]
    fn to_camel_converts_names() {
        assert_eq!(to_camel("NONE"), "None");
        assert_eq!(to_camel("PROTECTED_MEDIA"), "ProtectedMedia");
    }
}
