// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Jagadeesh Chandra Muddana <mjchandra@gmail.com>

//! C headers for the ABI/FFI boundary, emitted from the same compiled IR the
//! Rust bindings and the reference pages come from.
//!
//! **Why C, and why generated.** `docs/api/03` has said since it was written
//! that bindings are "Rust first-class; **C for the ABI/FFI boundary**", and
//! the C half had never been built — the tree had `codegen_rust`,
//! `codegen_fuzz` and `codegen_docs` and nothing that a C compiler could read.
//! That was affordable while everything targeting this system was written in
//! Rust here. It stops being affordable at the POSIX tier: a libc is C, a
//! ported toolchain is C, and neither can be handed a Rust `struct` definition
//! (`docs/roadmap/04`, Phase 3).
//!
//! **The header proves itself.** Every emitted struct carries a
//! `_Static_assert` for its size and one per field for its offset, against the
//! numbers the ISL compiler computed. So the claim "the C declaration and the
//! Rust one describe the same bytes" is not made by this file, or by a test
//! that reads it: it is made by the C compiler, on the target it is compiling
//! for, and a header whose layout disagrees does not compile. That is the
//! strongest form the claim can take, and it is why nothing here is `packed`
//! — a packed struct would *force* agreement and prove nothing about whether
//! the natural layout already agreed.
//!
//! **What is emitted, and what is not.** Frozen `@abi` structs, enums,
//! bitflags, syscall numbers and protocol ordinals — everything with a fixed
//! layout. Tables, unions, strings and vectors are out-of-line: their encoding
//! is the wire codec's and a C consumer needs that codec, not a struct
//! definition. They are listed in a comment rather than silently omitted, so a
//! reader of the header knows the schema had more in it.
//!
//! Output is byte-stable across rebuilds: declaration order is preserved and
//! nothing environment-derived is emitted. Generated headers are a build
//! output, never committed (docs/lifecycle/04-coding-guidelines.md).
//!
//! Normative: docs/api/03-interface-schema-language.md ("Generated Artifacts"),
//! docs/roadmap/04-self-hosting.md ("Phase 3")
//! Budget: none (build-time tooling)

use crate::ast::PrimType;
use crate::ir::{Ir, IrDecl, IrFieldType, IrMethodKind, IrStruct, IrSyscall};
use std::fmt::Write as _;

/// Emits the C header for `ir`.
pub fn emit(ir: &Ir) -> String {
    let prefix = prefix_of(&ir.library);
    let guard = format!("{}_H", prefix.to_uppercase());
    let mut out = String::new();

    let _ = writeln!(
        out,
        "/* @generated by islc emit-c — do not edit; regenerate from the schema. */"
    );
    let _ = writeln!(out, "/* Library: {} */", ir.library);
    if !ir.doc.is_empty() {
        for line in ir.doc.lines() {
            let _ = writeln!(out, "/* {line} */");
        }
    }
    let _ = writeln!(out, "#ifndef {guard}\n#define {guard}\n");
    // `stdint` for the fixed-width types the wire is defined in, `stddef` for
    // `offsetof`. Nothing else: a header that pulled in more would make the
    // ABI depend on whatever else that brought.
    let _ = writeln!(out, "#include <stdint.h>\n#include <stddef.h>\n");
    let _ = writeln!(out, "#ifdef __cplusplus\nextern \"C\" {{\n#endif\n");

    emit_enums(&mut out, ir, &prefix);
    emit_bits(&mut out, ir, &prefix);
    emit_structs(&mut out, ir, &prefix);
    emit_syscalls(&mut out, ir, &prefix);
    emit_protocols(&mut out, ir, &prefix);
    emit_omitted(&mut out, ir);

    let _ = writeln!(out, "#ifdef __cplusplus\n}}\n#endif\n");
    let _ = writeln!(out, "#endif /* {guard} */");
    out
}

/// `tessera.diagnostic` → `tessera_diagnostic`.
///
/// The whole library path, not its last component: C has no namespaces, and two
/// schemas may each declare a `Header`. A long name is the price of that and is
/// cheaper than a collision a linker reports.
fn prefix_of(library: &str) -> String {
    library.replace('.', "_").to_lowercase()
}

/// `DiagnosticRecord` → `diagnostic_record`, and `RED` → `red`.
///
/// **A boundary, not every capital.** Splitting before each uppercase letter
/// turns an already-shouting name into `_r_e_d`, which is what the first
/// version of this did to every enum member in the tree. An underscore goes in
/// where a *word* starts: after a lowercase letter or a digit, or before the
/// last capital of a run that is followed by a lowercase one, so `SYS_Debug`
/// and `HTTPServer` both come out right.
fn snake(name: &str) -> String {
    let chars: Vec<char> = name.chars().collect();
    let mut out = String::new();
    for (index, &ch) in chars.iter().enumerate() {
        if ch == '_' {
            if !out.ends_with('_') {
                out.push('_');
            }
            continue;
        }
        if ch.is_ascii_uppercase() && index != 0 {
            let prev = chars[index - 1];
            let next_is_lower = chars.get(index + 1).is_some_and(char::is_ascii_lowercase);
            let boundary = prev.is_ascii_lowercase()
                || prev.is_ascii_digit()
                || (prev.is_ascii_uppercase() && next_is_lower);
            if boundary && !out.ends_with('_') {
                out.push('_');
            }
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}

/// `Severity` → `TESSERA_DIAGNOSTIC_SEVERITY`.
fn screaming(prefix: &str, name: &str) -> String {
    format!("{}_{}", prefix, snake(name)).to_uppercase()
}

/// The C spelling of a primitive.
///
/// **`bool` is `uint8_t`, deliberately.** C's `_Bool` is one byte on every
/// target here, but its representation of values other than 0 and 1 is the
/// implementation's business, and this is a wire type: what crosses is a byte.
fn prim_c(p: PrimType) -> &'static str {
    match p {
        PrimType::Bool | PrimType::Uint8 => "uint8_t",
        PrimType::Int8 => "int8_t",
        PrimType::Int16 => "int16_t",
        PrimType::Int32 => "int32_t",
        PrimType::Int64 => "int64_t",
        PrimType::Uint16 => "uint16_t",
        PrimType::Uint32 => "uint32_t",
        PrimType::Uint64 => "uint64_t",
        PrimType::Float32 => "float",
        PrimType::Float64 => "double",
    }
}

/// The C type for a field, and the array suffix that follows its name.
fn c_type(ty: &IrFieldType, prefix: &str) -> (String, String) {
    match ty {
        IrFieldType::Prim(p) => (prim_c(*p).to_string(), String::new()),
        IrFieldType::Enum { name, .. } | IrFieldType::Bits { name, .. } => {
            (format!("{}_{}_t", prefix, snake(name)), String::new())
        }
        // A handle is an index into the receiving process's table, four bytes
        // wide. The object type and rights the schema declared are compile-time
        // facts about who may hold it, not part of its representation.
        IrFieldType::Handle { .. } => ("uint32_t".to_string(), String::new()),
        IrFieldType::Struct { name } => (format!("{}_{}_t", prefix, snake(name)), String::new()),
        IrFieldType::Array { elem, len } => {
            let (inner, suffix) = c_type(elem, prefix);
            (inner, format!("[{len}]{suffix}"))
        }
        // Unreachable in a frozen struct — `check.rs` refuses them there — and
        // spelled rather than panicking, because a backend that aborted on a
        // schema the checker accepts would be the one thing here that can stop
        // a build for no stated reason.
        IrFieldType::String { .. } | IrFieldType::Vector { .. } => {
            ("/* out-of-line */ void *".to_string(), String::new())
        }
    }
}

fn emit_enums(out: &mut String, ir: &Ir, prefix: &str) {
    for decl in &ir.decls {
        let IrDecl::Enum(e) = decl else { continue };
        let ty = format!("{}_{}_t", prefix, snake(&e.name));
        if !e.doc.is_empty() {
            for line in e.doc.lines() {
                let _ = writeln!(out, "/* {line} */");
            }
        }
        // **A typedef of the base type, not a C `enum`.** An enum's underlying
        // type is the implementation's choice; the wire's is the schema's, and
        // the two must not be allowed to differ.
        let _ = writeln!(out, "typedef {} {ty};", prim_c(e.base));
        for member in &e.members {
            let _ = writeln!(
                out,
                "#define {} (({ty})({}))",
                screaming(prefix, &format!("{}_{}", e.name, member.name)),
                member.value
            );
        }
        let _ = writeln!(out);
    }
}

fn emit_bits(out: &mut String, ir: &Ir, prefix: &str) {
    for decl in &ir.decls {
        let IrDecl::Bits(b) = decl else { continue };
        let ty = format!("{}_{}_t", prefix, snake(&b.name));
        if !b.doc.is_empty() {
            for line in b.doc.lines() {
                let _ = writeln!(out, "/* {line} */");
            }
        }
        let _ = writeln!(out, "typedef {} {ty};", prim_c(b.base));
        for member in &b.members {
            let _ = writeln!(
                out,
                "#define {} (({ty})({}))",
                screaming(prefix, &format!("{}_{}", b.name, member.name)),
                member.value
            );
        }
        let _ = writeln!(out);
    }
}

/// Whether every field of `s` has a fixed size, and so a C declaration.
///
/// **Not the same question as `@abi`.** `@abi` says a struct is *frozen* — its
/// layout may never change — where this asks whether it has one at all. The two
/// came apart the first time a frozen struct nested a plain one: `StartupArgs`
/// holds `array<StartupArg, 12>` and `StartupArg` carries no `@abi`, so a header
/// that emitted only frozen structs referred to a type it had not declared and
/// did not compile. A plain struct inside a frozen one is part of the frozen
/// layout whatever its own annotation says.
fn is_inline(s: &IrStruct) -> bool {
    !s.fields.iter().any(|f| {
        matches!(
            f.ty,
            IrFieldType::String { .. } | IrFieldType::Vector { .. }
        )
    })
}

fn emit_structs(out: &mut String, ir: &Ir, prefix: &str) {
    for decl in &ir.decls {
        let IrDecl::Struct(s) = decl else { continue };
        if !is_inline(s) {
            continue;
        }
        emit_struct(out, s, prefix);
    }
}

fn emit_struct(out: &mut String, s: &IrStruct, prefix: &str) {
    let ty = format!("{}_{}_t", prefix, snake(&s.name));
    let tag = format!("{}_{}_s", prefix, snake(&s.name));
    if !s.doc.is_empty() {
        for line in s.doc.lines() {
            let _ = writeln!(out, "/* {line} */");
        }
    }
    let _ = writeln!(out, "typedef struct {tag} {{");
    for field in &s.fields {
        if !field.doc.is_empty() {
            for line in field.doc.lines() {
                let _ = writeln!(out, "    /* {line} */");
            }
        }
        let (base, suffix) = c_type(&field.ty, prefix);
        let _ = writeln!(out, "    {base} {}{suffix};", field.name);
    }
    let _ = writeln!(out, "}} {ty};\n");

    // **The header's own conformance.** These are the numbers `islc` computed;
    // if the C compiler lays the struct out differently on the target it is
    // compiling for, this does not build. Nothing else in the tree has to check
    // it, and no test can check it as well: the assertion is made where the
    // layout is actually decided.
    let _ = writeln!(
        out,
        "_Static_assert(sizeof({ty}) == {}, \"{}: wire size\");",
        s.size, s.name
    );
    for field in &s.fields {
        let _ = writeln!(
            out,
            "_Static_assert(offsetof({ty}, {}) == {}, \"{}.{}: wire offset\");",
            field.name, field.offset, s.name, field.name
        );
    }
    let _ = writeln!(out);
}

fn emit_syscalls(out: &mut String, ir: &Ir, prefix: &str) {
    let syscalls: Vec<&IrSyscall> = ir
        .decls
        .iter()
        .filter_map(|d| match d {
            IrDecl::Syscall(s) => Some(s),
            _ => None,
        })
        .collect();
    if syscalls.is_empty() {
        return;
    }
    let _ = writeln!(out, "/* The call surface: one number per call. */");
    for call in &syscalls {
        if !call.doc.is_empty() {
            for line in call.doc.lines() {
                let _ = writeln!(out, "/* {line} */");
            }
        }
        let _ = writeln!(
            out,
            "#define {} ((uint64_t){})",
            screaming(prefix, &format!("SYS_{}", call.name)),
            call.number
        );
    }
    let _ = writeln!(out);
}

fn emit_protocols(out: &mut String, ir: &Ir, prefix: &str) {
    for decl in &ir.decls {
        let IrDecl::Protocol(p) = decl else { continue };
        let _ = writeln!(out, "/* protocol {} */", p.name);
        let _ = writeln!(
            out,
            "#define {} ((uint64_t)0x{:016x}ULL)",
            screaming(prefix, &format!("{}_INTERFACE_ID", p.name)),
            p.interface_id
        );
        for method in &p.methods {
            // **A reserved ordinal has no name**, and emitting one anyway
            // produced `..._BLOCK_DEVICE_` twice in `block_driver` — a macro
            // redefinition the C compiler refused, which is how this was found.
            // It is still worth saying: a consumer that reused the number would
            // be renumbering the protocol.
            if matches!(method.kind, IrMethodKind::Reserved) {
                let _ = writeln!(
                    out,
                    "/*   ordinal {} is reserved — do not reuse it */",
                    method.ordinal
                );
                continue;
            }
            let _ = writeln!(
                out,
                "#define {} ((uint32_t){})",
                screaming(prefix, &format!("{}_{}", p.name, method.name)),
                method.ordinal
            );
        }
        let _ = writeln!(out);
    }
}

/// Names what this header does not carry, rather than leaving a reader to
/// notice the schema had more in it.
fn emit_omitted(out: &mut String, ir: &Ir) {
    let mut omitted: Vec<String> = Vec::new();
    for decl in &ir.decls {
        match decl {
            IrDecl::Table(t) => omitted.push(format!("table {}", t.name)),
            IrDecl::Union(u) => omitted.push(format!("union {}", u.name)),
            IrDecl::Struct(s) if !is_inline(s) => omitted.push(format!("struct {}", s.name)),
            _ => {}
        }
    }
    if omitted.is_empty() {
        return;
    }
    let _ = writeln!(
        out,
        "/* Not in the C ABI surface, because their encoding is out-of-line and"
    );
    let _ = writeln!(
        out,
        "   a C consumer needs the wire codec rather than a struct definition:"
    );
    for name in &omitted {
        let _ = writeln!(out, "     {name}");
    }
    let _ = writeln!(out, " */\n");
}

#[cfg(test)]
#[path = "tests/codegen_c.rs"]
mod tests;
